import type { Metadata } from "next"
import { PT_Sans } from "next/font/google"
import "./globals.css"

const pt_sans = PT_Sans({
  weight: "400",
  variable: "--font-pt-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "James O'Neill",
  description: "Generated by create next app",
  authors: { name: "James O'Neill" },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pt_sans.className}>{children}</body>
    </html>
  )
}
